### ISSUE TITLE
Compari pointeri

### ISSUE THREAD

**Issue by alexandruradovici** [CAmi307/SDE_tp1#1]
https://github.com/CAmi307/SDE_tp1/blob/2edf89f9ccb18d29b514c79a7ae5f39cfc3b5fee/src/main.rs#L77

Tu in loc sa compari valoarea cu 1, compari adresa valorii cu adresa constantei 1. Ar trebui sa fie `*element < 1`

https://github.com/CAmi307/SDE_tp1/blob/2edf89f9ccb18d29b514c79a7ae5f39cfc3b5fee/src/main.rs#L105

Aceeasi problema aici

**Comment by CAmi307** [comment]
Am inteleees. Are sens. Da cum de a mers programu?

**Comment by alexandruradovici** [comment]
Adresa variabilei era mai mica decat a numarului (probabil). Poti scrie `println!("{:p} < {:p}", element, &1)` si vezi.

**Comment by CAmi307** [comment]
Aaaah. Got it. Multumesc :)

**Comment by alexandruradovici** [comment]
Incearca println!-ul, sunt curios daca asa e.

**Comment by CAmi307** [comment]
![Screenshot (754)](https://user-images.githubusercontent.com/101173949/158592991-b1f1dbcc-8910-4a20-b950-693d44259cdc.png)
 
am adaugat println-ul. intr-adevar adresa lui 1 e mai mare

**Comment by CAmi307** [comment]
Am dat push si la varianta corectata
